### ISSUE TITLE
2nd to N realizations on a saved set make the graph break until saved again

### ISSUE THREAD

**Issue by HenrikMoe** [HenrikMoe/CryptoCount#10]

**Comment by HenrikMoe** [comment]
Additional saves make the graph and sets smaller

**Comment by HenrikMoe** [comment]
<img width="764" alt="Screen Shot 2021-08-04 at 10 35 57 AM" src="https://user-images.githubusercontent.com/54423408/128227829-4c72ddb5-5e9a-439d-9e46-cb59a24cb9fe.png">

**Comment by HenrikMoe** [comment]
<img width="825" alt="Screen Shot 2021-08-04 at 10 35 26 AM" src="https://user-images.githubusercontent.com/54423408/128227892-0990b0d2-57a0-4ee7-ad33-11f4c75dfe2b.png">

**Comment by HenrikMoe** [comment]
<img width="839" alt="Screen Shot 2021-08-04 at 10 36 47 AM" src="https://user-images.githubusercontent.com/54423408/128227975-dbf6091c-8f7d-4dfd-b443-be93efb9986d.png">

**Comment by HenrikMoe** [comment]
Essentially, playing with Applying realizing and Saving them severly disconfigures the dataset. This issue might be in save realize on the server. Database should be updated before pathcing because correct data from server is dependent on database update

**Comment by HenrikMoe** [comment]
<img width="851" alt="Screen Shot 2021-08-04 at 10 37 54 AM" src="https://user-images.githubusercontent.com/54423408/128228263-fd4af047-dd81-4fbc-ba72-d5251b06e2d4.png">

**Comment by crbellis** [comment]
Not seeing weird issue with negative numbers after last push. however, each save only the most recent realized save data is returned. is this expected? otherwise the dataset reduces each time.
<img width="976" alt="Screen Shot 2021-08-07 at 4 49 04 PM" src="https://user-images.githubusercontent.com/63214891/128616468-c349bd10-d030-47f3-ab8a-cbf1ce3a6099.png">
<img width="978" alt="Screen Shot 2021-08-07 at 4 50 10 PM" src="https://user-images.githubusercontent.com/63214891/128616474-2aca53e3-4de1-477a-962e-bfd453b4e9f1.png">

Is this expected?

**Comment by HenrikMoe** [comment]
Unexpexted

**Comment by crbellis** [comment]
@HenrikMoe do you want the backend to return the full realized set? Or do you want to accommodate this on the frontend?

**Comment by HenrikMoe** [comment]
After saving, the backend should return the realized set yeah. It should be pushed into the users db model after they click save and then called back up to the client

**Comment by crbellis** [comment]
@cpshaheen for viz. basically just need to concat realized sets when a user saves and then return entire set

**Comment by crbellis** [comment]
@HenrikMoe  this is done
<img width="1009" alt="Screen Shot 2021-08-10 at 9 14 26 PM" src="https://user-images.githubusercontent.com/63214891/128968802-7ca22fcf-b8aa-4cc1-a732-4368d6bacb60.png">
<img width="993" alt="Screen Shot 2021-08-10 at 9 14 20 PM" src="https://user-images.githubusercontent.com/63214891/128968807-c1f865e0-b87a-4b97-9ca0-2caeeda5c3c7.png">
<img width="1026" alt="Screen Shot 2021-08-10 at 9 14 13 PM" src="https://user-images.githubusercontent.com/63214891/128968808-3f43237a-bd37-4489-81ab-90d83a2b4159.png">
