### ISSUE TITLE
Realized History tab doesnt load sets after clicking save in Analysis tab

### ISSUE THREAD

**Issue by HenrikMoe** [HenrikMoe/CryptoCount#11]

**Comment by HenrikMoe** [comment]
After saving a realize on the analysis page, the Realized history page doesnt update. Can we make this update live?

**Comment by crbellis** [comment]
Realized History now updates after a user saves a set. Currently filtering for sets where realizedBasisRewards.length > 1. if that should be some other logic lmk.

<img width="1156" alt="Screen Shot 2021-08-10 at 10 27 11 PM" src="https://user-images.githubusercontent.com/63214891/128975271-8a570613-5a87-4518-9345-21ea97ceff96.png">
<img width="666" alt="Screen Shot 2021-08-10 at 10 28 14 PM" src="https://user-images.githubusercontent.com/63214891/128975276-7195e24f-6473-4c17-b4a6-0e9ee400abb5.png">
<img width="1601" alt="Screen Shot 2021-08-10 at 10 14 47 PM" src="https://user-images.githubusercontent.com/63214891/128975278-bb77f581-7ff1-4d56-afd5-eec71aff002f.png">

**Comment by crbellis** [comment]
closing this but if we need to change logic for currently display history then can reopen. or create another ticket, since that is different issue.
