### ISSUE TITLE
Add MAX REWARDS button to quantity realized field which fills in unrealizdRewardAgg api property

### ISSUE THREAD

**Issue by HenrikMoe** [HenrikMoe/CryptoCount#15]

**Comment by HenrikMoe** [comment]
Client must take unreLized payload from auto and maunal and extract unrealizedRewardAgg, place in realize quanitity field as selectable MAX value

**Comment by HenrikMoe** [comment]
Feature greatly helps put guardrails around the main feature of the application - realizing block rewards passively annually

**Comment by crbellis** [comment]
feature add
