### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by songproducer** [HenrikMoe/CryptoCount#4]
After cding into backend and running:
npm start main.js

```
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

**Comment by HenrikMoe** [comment]
after cding into backend run: 
node main.js <portnumber>

**Comment by HenrikMoe** [comment]
Hey I just read your logic in your baker accounting project. Let's connect, I think we can work together on this project. telegram: @HenrikMoe
