### ISSUE TITLE
Basis Bar and “realize history” bar need to be combined

### ISSUE THREAD

**Issue by HenrikMoe** [HenrikMoe/CryptoCount#9]

**Comment by HenrikMoe** [comment]
Below the graph needs to be the basis bar, the basis Price and the little country flag, all on one line. Currenctly its the basis bar and then below is the basis price realize History, which can be deleted, and the basis Price without the basis Price. So again, its little flag, basis bar, basisPrice - can you use the basisPrice thats returned from the server there?

**Comment by HenrikMoe** [comment]
<img width="773" alt="Screen Shot 2021-08-04 at 10 31 21 AM" src="https://user-images.githubusercontent.com/54423408/128227231-2ae59963-0bf3-48ef-b550-4eb36799ed25.png">

**Comment by HenrikMoe** [comment]
Above into one

**Comment by crbellis** [comment]
basis bas moved to chart params, not seeing basis balance in response
<img width="322" alt="Screen Shot 2021-08-07 at 4 42 50 PM" src="https://user-images.githubusercontent.com/63214891/128616395-d4efaad9-36b2-4eea-9b17-25d10409e8d9.png">

**Comment by HenrikMoe** [comment]
That is an old user object. Up to date user object has all properties

**Comment by crbellis** [comment]
updated
